### ISSUE TITLE
How to use serve-static?

### ISSUE THREAD

**Issue by lygstate** [carlosmarte/karma-framework-serve-static#1]

**Comment by carlosmarte** [comment]
Hi @lygstate please checkout the example in the repo.
https://github.com/carlosmarte/karma-framework-serve-static/tree/master/example

#### How to use serve-static
The before and after takes an array of static files.
The files in the before collection will load before any karma script
The files in the after collection will load after all karma script(bottom of the page)

The following configuration will put a before.js as the top most file and after.js at the bottom 
```js
module.exports = function(config) {
  config.set({
    ....
    serveStaticFramework:{
      before: [
        './scripts/before.js'
      ],
      after: [
        './scripts/after.js'
      ],
    },
    ....
};
```

#### Example:
```html
<script type="text/javascript" src="/base/scripts/before.js"></script>
<script type="text/javascript" src="/base/node_modules/mocha/mocha.js"></script>
<script type="text/javascript" src="/base/node_modules/karma-mocha/lib/adapter.js"></script>
<script type="text/javascript" src="/base/chai.js"></script>
<script type="text/javascript" src="/base/specs.js"></script>
<script type="text/javascript" src="/base/scripts/after.js"></script>
```

this is ideal for loading vendor files that you would need before any script runs or after. 

At the current moment, I don't have much time for after work coding. but i will try to update the document next weekend. best carlos
